### ISSUE TITLE
Some blocks are not clickable but are styled as if they are

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes-bootcamp#11]
First page:

We already installed minikube for you. Check that it is properly installed, by running the `minikube version` command:

`minikube version ↵`

Both of these are styled as if they should be clickable, but only the second one does anything.

**Comment by jocatalin** [comment]
By default, there is only one styling for code: the black background styling. ( @benhall please correct me here if I'm wrong.   The execution of blocks of code is available only for the blocks that carry a special tag (the enter sign). If this is confusing, I can remove completely the styling from the commands that are not supposed to be executed. @pwittrock what do you think?

**Comment by BenHall** [comment]
On Katacoda I use _italics_ to highlight commands and filenames...
