### ISSUE TITLE
Katacoda introduction screens

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes-bootcamp#12]
![screen shot 2016-08-10 at 4 42 54 pm](https://cloud.githubusercontent.com/assets/132510/17560314/8929ee44-5f19-11e6-81bd-960114cefd35.png)
- The whole block, but particularly the text "Welcome" feels too big to me - the balance on later screens is much better
- It need not say 'jocatalin'
- `block of code` isn't in the same style as on later screens

**Comment by jocatalin** [comment]
@benhall can you advice on this?  the `block of code` was also mentioned here: https://github.com/ContainerSolutions/kubernetes-bootcamp/issues/11

**Comment by BenHall** [comment]
@jocatalin I'm guessing you want this to look like it can be execute, but not actually run the code?

**Comment by jocatalin** [comment]
Actually the intent was to show just that those are kubectl commands (use a different styling) compared to plain text.

**Comment by BenHall** [comment]
@jocatalin So it should have the black background?

**Comment by jocatalin** [comment]
@BenHall I would like to have a different styling compared to regular text. It shouldn't have the black background.
