### ISSUE TITLE
Terminal is active but not encouraged

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes-bootcamp#14]
You can type in the terminal, but it's not made obvious with the instructions, which just say 'click the blocks'.  We could make it more obvious that it is possible to interact in any way you wish.

When you get to the second module, you're running kubectl proxy, and it says "open another terminal window" - it confused me for a second that you do that with the +, so perhaps a primer to the environment might be a good idea somewhere?

(Also, I can connect to things with nc, which you might not expect should be possible.)

**Comment by jocatalin** [comment]
I changed the description from the first page of the scenarios with: 
The online terminal is a pre-configured Linux environment that can be used as a regular console (you can type commands). 
Clicking on the `blocks of code` followed by the ENTER sign will execute that command in the terminal.

I changed the part frm module 2 which was confussing. Can you please review it and let me know.

What are your concerns related to nc? Security?

**Comment by craigbox** [comment]
Yeah, I don't know where Katacoda is hosted, but I don't know if it's a problem that users can make arbitrary outgoing connections.  Though I guess there's nothing stopping them doing it with containers they download into their Kube environment - so it's not about nc but about outgoing connections. Something I noticed.

**Comment by jocatalin** [comment]
Let's ask  Ben (founder of Katacoda): @benhall as users don't need to login to access the terminal, there are some security concerns that this can be abused. What's your opinion about this?

**Comment by BenHall** [comment]
Thank you for the feedback Craig. We haven't had any problems on Katacoda site where we also don't require user authentication. If people really want to mis-use the platform they will find a way, for example, via a container. We have monitoring and checking in place to migrate against certain problems. I'm always reviewing how the platform is being used and updating where required.

I talked about some of the issues in my container camp 2015 talk - https://www.youtube.com/watch?v=EJ9ey6-DbGM
