### ISSUE TITLE
Lots of dead space

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes-bootcamp#16]
Screens like https://containersolutions.github.io/kubernetes-bootcamp/2-0.html have a lot of vertical whitespace which forces me to scroll down for no real value

**Comment by jocatalin** [comment]
@thockin can you check again, I removed this from 6 pages (1-0, 2-0, ....)

**Comment by thockin** [comment]
better.  I still have to maximize a browser window on my 1600x900 laptop to see the -0 pages in one screen.
