### ISSUE TITLE
click link in interactive mode, pastes wrong text

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes-bootcamp#17]
https://containersolutions.github.io/kubernetes-bootcamp/2-2.html

When I click "kubectl run kubernetes-bootcamp --image=docker.io/jocatalin/kubernetes-bootcamp:v1 --port=8080" what gets pasted is "o/jocatalin/kubernetes-bootcamp:v1 --port=8080cker.i"

**Comment by thockin** [comment]
It looks like line-wraps are over-writing the same line.

**Comment by BenHall** [comment]
Thanks for the feedback Tim. This is a known issue with Javascript terminal emulators at the moment. I'm currently working on a fix which I hope to push upstream.

**Comment by BenHall** [comment]
Hi Tim,

I took another look at this and deployed a fix this morning. The command now wrap onto the next line.

![screenshot 2016-08-12 12 55 10](https://cloud.githubusercontent.com/assets/82614/17621568/0aaa02d8-608c-11e6-8f16-98693c1fbabf.png)

**Comment by thockin** [comment]
looks good
