### ISSUE TITLE
Not enough screen real estate

### ISSUE THREAD

**Issue by jeffmendoza** [kubernetes/kubernetes-bootcamp#20]
Trying to do the steps in the tiny katakoda terminal is really difficult. You should be able to collapse the left nav to get a larger terminal.

**Comment by jeffmendoza** [comment]
Example below. This is 1500 px wide, but still a tiny terminal.
![k8s-bootcamp-2](https://cloud.githubusercontent.com/assets/771387/17598924/9f5dbdf6-5fb1-11e6-88dd-5ec64e640cfc.png)

**Comment by jocatalin** [comment]
Jeff, I warned @pwittrock & co about this. You (I mean Google) insisted to have the menu always there on desktop version. Initially it was designed to collapse also on desktop (as it happens on tablets). @pwittrock it's your call on this one. I know it was an explicit request from your side to always keep the menu visible on desktop.

**Comment by pwittrock** [comment]
@jeffmendoza Having the sidebar automatically collapse / expand on mouse hover was a really jarring experience.

**Comment by jeffmendoza** [comment]
Maybe it should expand on click instead?

**Comment by jocatalin** [comment]
We'll look into adding the arrow that allows users to expand/hide the menu on desktop. Like on tablet.

**Comment by yissachar** [comment]
I'll just point out that the terminal in the screenshot has a huge left margin that shouldn't be there. Playing around with resizing my browser window I see that under certain sizes this effect shows up and other times I end up with a large amount of dead space on the right.

Fixing the terminal to use 100% of the available space, as well as general margin tweaks (do you really need 60px left/right padding on the main content?), would go a long way to improving space utilization without needing to collapse the sidebar.

**Comment by BenHall** [comment]
@yissachar Yes, you're right, it shouldn't be there. It looks like Chrome on Windows introduced a hidden scrollbar that pushed the terminal window over. I've updated the CSS so you shouldn't see this gap. If you could re-test that would be a great help.


This is how it now looks on Windows 10 Edge via Browserstack on a 1024x768 res.
![win10_edge_13 0](https://cloud.githubusercontent.com/assets/82614/17836966/0811a2b0-679e-11e6-91c6-23ca7885430b.png)

**Comment by jeffmendoza** [comment]
Here is what I'm seeing today.  The margin on the right of the terminal looks too large.
![katakoda term](https://cloud.githubusercontent.com/assets/771387/17861168/d98a322a-6844-11e6-8d1e-980d4af0cfff.png)

**Comment by BenHall** [comment]
What's your browser / OS?

**Comment by jeffmendoza** [comment]
Ubuntu 14.04
Chrome Version 53.0.2785.57 beta (64-bit)

**Comment by jeffmendoza** [comment]
Some more screenshots if it helps.
![inner square](https://cloud.githubusercontent.com/assets/771387/17861504/39b54922-6846-11e6-984e-61c1e539bc49.png)
![outer square](https://cloud.githubusercontent.com/assets/771387/17861505/39b5c0c8-6846-11e6-97dd-b6fe2ffa3f33.png)

**Comment by yissachar** [comment]
@BenHall Left margin seems to be gone now 👍 

But I'm seeing the same thing as @jeffmendoza with the too-large right margin.

Mac OS X 10.11.5
Chrome 52.0.2743.116 (64-bit)

**Comment by BenHall** [comment]
I've removed the margin, let me know your thoughts.

**Comment by yissachar** [comment]
@BenHall I'm not seeing any change on https://kubernetesbootcamp.github.io

The Katacoda site has good margins, but I didn't take a look before so I'm not sure if that's the result of your update or if the Katacoda and Kubernetes Bootcamp sites are just rendering differently.

**Comment by BenHall** [comment]
This is my view:

![screenshot 2016-08-22 18 53 32](https://cloud.githubusercontent.com/assets/82614/17865289/c4b1ad4c-6899-11e6-9538-20109a02b2d0.png)

**Comment by yissachar** [comment]
I see a large amount of right margin:

![screen shot 2016-08-22 at 1 58 11 pm](https://cloud.githubusercontent.com/assets/2190867/17865478/c11023b8-6870-11e6-8606-75b9dae37539.png)

Compare that with the Katacoda site, where the text goes to the edge of the terminal (with a tiny amount of margin)

![screen shot 2016-08-22 at 1 58 59 pm](https://cloud.githubusercontent.com/assets/2190867/17865496/cb60eb68-6870-11e6-9dbc-74e3b88b88cd.png)

**Comment by jocatalin** [comment]
I pushed a change that allows hiding the menu also on desktop. was just merged.
