### ISSUE TITLE
Katakoda instruction text gets huge when window is large

### ISSUE THREAD

**Issue by jeffmendoza** [kubernetes/kubernetes-bootcamp#21]
When I maximize my window, the instruction text in katakoda gets huge.
![k8s-bootcamp](https://cloud.githubusercontent.com/assets/771387/17598411/38c0ebb0-5faf-11e6-9d9a-7260d71b1c08.png)

**Comment by jocatalin** [comment]
@benhall the resolution for this example is 2542 × 1021 this be fixed?

**Comment by BenHall** [comment]
This was an intentional design, however I've never been 100% sure about it.

I've removed it and I'll deploy the change tomorrow.
