### ISSUE TITLE
Error after "Next Scenario" in Katakoda

### ISSUE THREAD

**Issue by jeffmendoza** [kubernetes/kubernetes-bootcamp#22]
After completing a scenario in Katakoda, click the right arrow after "Step X of X" and you see a "Congratulations!" screen with a "Next Scenario" button. Clicking that button results in:

> Coming Soon
> Sorry, it looks like you've come across something not quite ready yet, bare with us.

**Comment by jocatalin** [comment]
I'll probably remove that last page if we can't customize it.  Can we @benhall ? The "next" scenario button doesn't make sense here, as it breaks the current workflow: learn-> try interactive -> quiz

**Comment by BenHall** [comment]
Couple of options.

1) Set the data-katacoda-ctatext and data-katacoda-cta (for the link) attributes. You can then direct them to the quiz...
2) Set the attribute data-katacoda-hidefinish=true - This will disable the final finish dialog.
