### ISSUE TITLE
Screen before quiz not needed

### ISSUE THREAD

**Issue by jeffmendoza** [kubernetes/kubernetes-bootcamp#25]
From @craigbox:

> Also, after clicking this, I get a page where my only action is to click 'begin'. I would expect to be taken straight into the quiz.

**Comment by jocatalin** [comment]
I'll remove this and create a PL for review. The text from the screen before quiz will be moved to the quiz screen:
![screen shot 2016-08-12 at 16 20 51](https://cloud.githubusercontent.com/assets/4931072/17625402/0bd57c88-60a9-11e6-9154-0e8fb3a06ad0.png)

**Comment by craigbox** [comment]
There's no quiz now.

/close
