### ISSUE TITLE
Module Quiz "Leave us comment" Section's popup message

### ISSUE THREAD

**Issue by puneith** [kubernetes/kubernetes-bootcamp#27]
When I took the quiz and was asked to leave us a comment. In the pop up it says "Sample Question" and that title doesn't seem appropriate. (Screenshot attached) - kubernetes-bootcamp.png
![kubernetes-bootcamp](https://cloud.githubusercontent.com/assets/8098778/17634869/614a0d7a-6089-11e6-9dc0-f7d4239743d3.png)

**Comment by jocatalin** [comment]
This will be linked to open new issue in github. URL to the repo was not know at the moment of publishing. Thanks for reporting this.
