### ISSUE TITLE
Diagram of node not 100% clear

### ISSUE THREAD

**Issue by puneith** [kubernetes/kubernetes-bootcamp#28]
This diagram of node here https://kubernetesbootcamp.github.io/kubernetes-bootcamp/3-1.html leaves some doubt about whether there is one docker or multiple in the node. You have shows Docker next to kubelet thereby causing some confusion.

**Comment by jocatalin** [comment]
The text above the diagram mentions:

*Every Kubernetes Node runs at least:
A container runtime (like Docker, rkt) that will take care of pulling all your containers from a registry.
Kubelet, that acts as a bridge between the Kubernetes Master and the Nodes; it manages the Pods and the containers running on a machine.*
