### ISSUE TITLE
The Bootcamp is making is too easy to execute commands

### ISSUE THREAD

**Issue by puneith** [kubernetes/kubernetes-bootcamp#29]
Its great to see the Bootcamp walk me through the commands to the degree that I am almost feeling no friction at all. But at the same time, that is not a great thing either because I may not have learn about the commands and interaction at the end of the bootcamp. I propose you keep how things are but also introduce a way for user to encounter friction (user typing the commands himself). And then at the end of each module may be you can tell him e.g, how many commands he typed etc.

**Comment by jocatalin** [comment]
The terminal is accessible to the users. Check the comments from https://github.com/kubernetes/kubernetes-bootcamp/issues/14 I'm going to make this even more explicit. 
In the 2nd scenario when I introduce kubectl, I encourage users to interact with the terminal:
_Like minikube, kubectl comes installed in the online terminal. Type kubectl in the terminal to see its usage.
The common format of a kubectl command is: kubectl action resource
This performs the specified action (like create, describe) on the specified resource (like node, container). You can use `--help` after the command to get additional info about possible parameters (`kubectl get nodes --help`)."_
Every bootcamp module was designed to go thought 3 stages: learn (the theory) - > The interactive console - > Quiz 
We do challenge the knowledge of kubectl commands in the quiz, and encourage people to interact with the terminal.
