### ISSUE TITLE
nit: terminal prompt should be $, not >

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes-bootcamp#32]
to most UNIX heads, `$` is the non-root prompt and `#` is the root prompt.  The current terminal uses `>` which generally means a line-continuation in bash.  I suggest changing > to $

**Comment by BenHall** [comment]
Thank you for the suggestion Tim, you make a very valid point. 

The motivation for "> " was to make it feel more welcoming as the $ symbol was confusing for those coming from a Windows background. I wanted users to start exploring and engaging with the terminal so a prompt of an arrow where users could type seemed to fit.

I'd be interested in hearing the views from the community on which is preferred.
