### ISSUE TITLE
Interactive instructions headers not using correct font

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kubernetes-bootcamp#37]
It's quite jarring compared to the rest of the page. It looks like it is supposed to be using Roboto Slab but isn't for some reason.

**Comment by BenHall** [comment]
This has been resolved.

**Comment by BenHall** [comment]
I've also fixed the title

![screenshot 2016-08-21 15 52 44](https://cloud.githubusercontent.com/assets/82614/17837912/523f73da-67b7-11e6-9e4b-c0afcaa030a2.png)

**Comment by yissachar** [comment]
Looks great now, thanks!
