### ISSUE TITLE
kubernetesbootcamp.github.io doesn't work due to banned CDN IPs in Russia

### ISSUE THREAD

**Issue by AlekSi** [kubernetes/kubernetes-bootcamp#46]
https://kubernetesbootcamp.github.io/kubernetes-bootcamp/1-2.html tries to load https://katacoda.com/embed.js and fails. If you go to http://katacode.com you will see that domain expired.

---

As a side note, this repository doesn't really have a link to kubernetesbootcamp.github.io, and that site doesn't have a link back to this repository.

**Comment by BenHall** [comment]
Hi @AlekSi 

I'm not seeing a problem. The domain is due to expire 2016-10-02T14:26:25Z according to whois db. Our SSL certification is valid until 23rd October. 

This is also reporting that the service is up - http://www.downforeveryoneorjustme.com/katacoda.com/

Our health checks and live traffic is also appearing it's live. Could this be an ISP problem? Could you send a screenshot of the error.

Thank you

Ben

**Comment by AlekSi** [comment]
![2016-09-09_14-00-55](https://cloud.githubusercontent.com/assets/11512/18384907/6c21b39e-769e-11e6-81e7-3f3cce4d1298.png)

https://katacode.com/ just doesn't load.

It certainly can be an ISP problem (or more like Russian government problem), but I also tried to load https://katacoda.com/embed.js from different locations via Tor browser – doesn't work too.

**Comment by BenHall** [comment]
Our domain is https://katacoda.com (a not e)

**Comment by AlekSi** [comment]
Doh. You are right, sorry for the confusion. At the moment https://katacoda.com/embed.js doesn't work for me due ISP blacklist (my guess it uses CloudFlare CDN?). Is it possible to move this script to main domain?

**Comment by BenHall** [comment]
Ahh. Yes, it's Cloudflare DNS/CDN. There should be a warning displayed if embed.js cannot be loaded for any particular reason.

**Comment by AlekSi** [comment]
There is no normally visible warning when I go to https://kubernetesbootcamp.github.io/kubernetes-bootcamp/1-2.html. There is an error in console. Also, if I try to open https://katacoda.com/embed.js directly, there is an error. In short, some IP addresses of CloudFlare are legally banned in Russia, so ISPs are doing MITM, providing their own TLS certificates.

So. I'm not sure if you want to move this script to `public` folder with other scripts instead of loading it from other domain, but it will definitely help people like me.

**Comment by AlekSi** [comment]
And if I try to use Tor, CloudFlare doesn't like it: https://blog.torproject.org/blog/trouble-cloudflare. So I have to go to https://katacoda.com/embed.js directly, solve CAPTACH, then go back to bootcamp.
