### ISSUE TITLE
Where is the Bootcamp content hosted

### ISSUE THREAD

**Issue by RobDolinMS** [kubernetes/kubernetes-bootcamp#54]
1. Browse to
2. Scroll down to the text
RESULT: No link to actually read the bootcamp content
EXPECT: Link to the index of the bootcamp content

**Comment by BenHall** [comment]
Hi Rob,

The content is hosted on the main Kubernetes website at http://kubernetes.io/docs/tutorials/kubernetes-basics/


Thanks

Ben
