### ISSUE TITLE
Clicking "continue" from interactive tutorial creates pop-up warning about leaving the page

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes-bootcamp#6]

**Comment by BenHall** [comment]
Which scenario do you see this on?

**Comment by pwittrock** [comment]
All of them.  Steps to reproduce:

https://containersolutions.github.io/kubernetes-bootcamp/1-2.html

On a Chrome browser: 
- Go to the interactive tutorial
- Click `minikube version`
- Click Module 1 quiz
- Pop comes up asking if you want to leave the page

**Comment by craigbox** [comment]
Also, after clicking this, I get a page where my only action is to click 'begin'.  I would expect to be taken straight into the quiz.

**Comment by jocatalin** [comment]
@craigbox that's the agreed workflow/design: that you shouldn't jump directly into the quiz, but have an intermediate screen.

**Comment by BenHall** [comment]
@pwittrock This is by design. It's to stop users mid-way from accidentally closing the tab. I'll let @jocatalin decide if it should be disabled or not.

**Comment by craigbox** [comment]
@pwittrock re. the jumping into the quiz - what purpose is the intermediate screen supposed to serve?  It could be enhanced by adding some text and/or having a "Skip" button?

(I was further surprised there was only one question in the quiz)

**Comment by jeffmendoza** [comment]
Looks like if you move past the last step (click the arrow after "Step X of X") to the "Congrats" screen, you don't get the popup. 

Is there a way to add a "Continue" button to the last step that moves to the "Congrats" screen? This could solve this issue, however #22 would be a bigger issue

**Comment by jeffmendoza** [comment]
@craigbox I created a separate issue for your comment #25

**Comment by craigbox** [comment]
There's no longer a quiz.

/close
