### ISSUE TITLE
Broken code in repository?

### ISSUE THREAD

**Issue by itilitymaarten** [kubernetes/kubernetes-bootcamp#70]
Hey guys,

First of all, I love this demo and the way that it's set up. Just a quick intro into how everything works, in the browser, it's great :)

However, I did notice some odd things in the code here in the repository. First of all, the javascript code for the v2 application still returns v=1, according to the code (`response.end(" | v=1\n");`). However, the actual demo nicely returns v=2.

Additionally, and this is one I am less sure of due to my limited experience with Docker: in the Dockerfile, it says `EXPOSE 8080`, which I assume means make port 8080 available to requests from outside the container. However, in the v1 application (not v2, just v1), the server is started on 8081 (`www.listen(8081,function () {`).

Are these two just mismatches in the code, that have been fixed for the actual demo, or am I missing something here?

**Comment by BenHall** [comment]
Thanks for highlighting this. You are completely correct that it's confusing. I've fixed it with #71

**Comment by itilitymaarten** [comment]
So you've now moved the standard Dockerfile to the v1 repository, but doesn't that still contain the mismatch, where the Dockerfile specifies port 8080, but the actual code uses port 8081?

**Comment by BenHall** [comment]
Thanks, I didn't realise v1 was also incorrect. Updated the PR
